config:
  spawn-location:
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0
    pitch: 0

  start-location:
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0
    pitch: 0

  spectator-location:
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0
    pitch: 0
